### ISSUE TITLE
Firebase session filter

### ISSUE THREAD

**Issue by Nishant-Pathak** [savicprvoslav/Spring-Boot-starter#1]
First of all thanks @savicprvoslav for such an effort and contribution, this is only the repo which I can find for firebase integration to springboot and it is working well. Do you have plans to have session based filter also ?

**Comment by savicprvoslav** [comment]
Hi, 
 thank you.

Can you say a few words on the session filter and why is it important for you. Then I can add it so that fits well within your use case.

Thanks.

**Comment by Nishant-Pathak** [comment]
I am using it in my app which is common entry point for app and web, All users login in have some roles and on that basis they have some session id which is save in cookie. And I am using that cookie to retrieve the session and hence to get the method level security.

**Comment by savicprvoslav** [comment]
I see, 
 are you referring to this http://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot.html ?

**Comment by Nishant-Pathak** [comment]
Yes, just in place of redis, I am using mongo. http://docs.spring.io/spring-session/docs/current/reference/html5/guides/mongo.html

**Comment by savicprvoslav** [comment]
Thank you, 
 let me look into this and get back to you soon.

**Comment by Nishant-Pathak** [comment]
Thanks, I would be happy to contribute too if you can guide.

**Comment by Nishant-Pathak** [comment]
Hi @savicprvoslav, I have add some code and find out, Onceperrequest filter works with session also and it is setting cookie "SESSION" on the browser. So, no worries and thanks. Respective code change can be found at https://github.com/Nishant-Pathak/Spring-Boot-starter
