### ISSUE TITLE
client app

### ISSUE THREAD

**Issue by svennela** [savicprvoslav/Spring-Boot-starter#3]
Hi,

Do you have angular client for this application? or I did mvn spring-boot:run it works fine. 

Sridhar

**Comment by savicprvoslav** [comment]
I had angular and android clients based on firebase to test the backend  but those are not available on github .

**Comment by qamalyanaren** [comment]
added android client please.....

**Comment by savicprvoslav** [comment]
Thanks, 
  I will add the simple clients just to prove the concept.

**Comment by qamalyanaren** [comment]
Tanks!!!
