### ISSUE TITLE
FirebaseUserNotExistsException

### ISSUE THREAD

**Issue by re-pvsr** [savicprvoslav/Spring-Boot-starter#4]
Issue resolved now thanks.

**Comment by re-pvsr** [comment]
Just to be clear, is the Exception thrown on purpose for a newsignup user ? I feel it should be routed to the new user registration(or something like that) instead of loadByUser.

Thanks.

**Comment by savicprvoslav** [comment]
Hi, 
 I have android firebase app that works correctly with this backend. I will check if all works correctly and write back.

API client is generated using swagger.

**Comment by savicprvoslav** [comment]
Hi, 
 I generated my android client using swagger as I said and was able to register the user normally. Also API calls worked nice with authentication.

Let me know if you were able to make it work.
Thanks.

**Comment by re-pvsr** [comment]
I think you will be able to register user1 and admin normally.
What about a new user signup, say user2 signs up with firebase and hits the /api/open/firebase/signup endpoint ? I think that will throw an error. At least that was what was happening for me.

**Comment by re-pvsr** [comment]
Also, these two parts of the code will create multiple USER_ROLE items in the DB. That is probably not what you intended. Please correct me if I am wrong.

```
private List<RoleEntity> getAdminRoles(){
		return Collections.singletonList(new RoleEntity(Roles.ROLE_ADMIN));
	}

```


        private List<RoleEntity> getUserRoles() {
		return Collections.singletonList(new RoleEntity(Roles.ROLE_USER));
	}`

Thanks.

**Comment by savicprvoslav** [comment]
I tried up to 5 users in total this is how many accounts I had at the moment. 

Code that you have sent is used in the init method that is designed to create some of the users initially( should be removed for any application that is created for real). So as a result two roles should be created, admin and user. This feels right to me.

**Comment by re-pvsr** [comment]
Point1: I am not able to understand the workflow of new registration. Probably something different in our workflows. My worflow is a firebase registered user hits our database and has to be created as a new user immediately. But as per the code, since the loadUserByUserName fails, it gives an error. Maybe your flow is different, but i am struggling to understand how you didn't get an error in new user registration.

Point2: ok am with you on this one.

Thanks.

**Comment by savicprvoslav** [comment]
When user authenticates it calls the signup if user does not exist it is created.

If user exists if fails, this is handled by the client. You can alter how repeated signup is handled, here is an example:

- If user does not exist it is created and HTTP201 is returned (CREATED)
- if user exists then return HTTP 200 saying OK

I hope this solves it, let me know.
